// Generated by CoffeeScript 1.7.1
(function() {
  var cmd, commander, fs, log, nurl, parse, path, request, run, save, serialize;

  fs = require('fs');

  nurl = require('url');

  path = require('path');

  request = require('superagent');

  commander = require('commander');

  cmd = function(args) {
    return new commander.Command().option('-m, --method <method>', "The http request method to use", 'GET').option('-u, --url <url>', "The url to hit").option('-f, --file <file>', "Where the file should be saved", './data.json').option('-a, --auth <username>:<password>', "Basic auth").option('-d, --data <data>', "Request body data").option('--nojson', "If this is not a json request").parse(args);
  };

  serialize = function(recq, res) {
    return {
      request: serialize.req(recq),
      response: serialize.res(res)
    };
  };

  serialize.req = function(recq) {
    var d;
    d = {
      method: recq.method,
      url: recq.url
    };
    if (recq.data) {
      d.body = recq.data;
    }
    return d;
  };

  serialize.res = function(res) {
    var d;
    d = {
      code: res.statusCode
    };
    if (res.body) {
      d.body = res.body;
    }
    return d;
  };

  save = function(recq, res, data) {
    var d;
    d = serialize(recq, res);
    data.push(d);
    return fs.writeFileSync(recq.file, JSON.stringify(data, null, 2));
  };

  parse = function(recq) {
    var _ref;
    recq.json = !recq.nojson;
    if (recq.auth) {
      _ref = recq.auth.split(':'), recq.username = _ref[0], recq.password = _ref[1];
    }
    recq.method = recq.method.toUpperCase();
    if (recq.data && recq.json) {
      recq.data = JSON.parse(recq.data);
    }
    return recq.file = path.resolve(recq.file);
  };

  log = function(recq, res) {
    if (require.main === module) {
      return console.log("(" + res.status + ") " + res.text);
    }
  };

  run = function(args, done) {
    var data, recq, req;
    recq = cmd(args);
    parse(recq);
    if (fs.existsSync(recq.file)) {
      data = require(recq.file);
    } else {
      data = [];
    }
    req = request(recq.method, recq.url);
    if (recq.username != null) {
      req.auth(recq.username, recq.password);
    }
    if (req.json) {
      req.type('application/json');
    }
    if (recq.data) {
      req.send(recq.data);
    }
    return req.end(function(res) {
      log(recq, res);
      save(recq, res, data);
      if (done != null) {
        return done(res);
      }
    });
  };

  exports.run = run;

  if (require.main === module) {
    run(process.argv);
  }

}).call(this);
